export interface CountryCode {
    name: string;
    code: string;
  }

export const COUNTRY_CODES = [
    { name: "United States", code: "+1" },
    { name: "Mexico", code: "+52" },
    { name: "United Kingdom", code: "+44" },
    { name: "Australia", code: "+61" },
    { name: "India", code: "+91" },
    { name: "Germany", code: "+49" },
    { name: "France", code: "+33" },
    { name: "Italy", code: "+39" },
    { name: "Spain", code: "+34" },
    { name: "China", code: "+86" },
    { name: "Japan", code: "+81" },
    { name: "South Korea", code: "+82" },
    { name: "Brazil", code: "+55" },
    { name: "Argentina", code: "+54" },
    { name: "South Africa", code: "+27" },
    { name: "Nigeria", code: "+234" },
    { name: "Egypt", code: "+20" },
    { name: "Russia", code: "+7" },
    { name: "Ukraine", code: "+380" },
    { name: "Saudi Arabia", code: "+966" },
    { name: "United Arab Emirates", code: "+971" },
    { name: "Israel", code: "+972" },
    { name: "Singapore", code: "+65" },
    { name: "New Zealand", code: "+64" },
    { name: "Philippines", code: "+63" },
    { name: "Pakistan", code: "+92" },
    { name: "Bangladesh", code: "+880" },
    { name: "Turkey", code: "+90" },
    { name: "Vietnam", code: "+84" },
    { name: "Thailand", code: "+66" },
    { name: "Malaysia", code: "+60" },
    { name: "Indonesia", code: "+62" },
    { name: "Colombia", code: "+57" },
    { name: "Venezuela", code: "+58" },
    { name: "Peru", code: "+51" },
    { name: "Chile", code: "+56" },
    { name: "Poland", code: "+48" },
    { name: "Netherlands", code: "+31" },
    { name: "Belgium", code: "+32" },
    { name: "Switzerland", code: "+41" },
    { name: "Sweden", code: "+46" },
    { name: "Norway", code: "+47" },
    { name: "Denmark", code: "+45" },
    { name: "Finland", code: "+358" },
    { name: "Portugal", code: "+351" },
    { name: "Greece", code: "+30" },
    { name: "Ireland", code: "+353" },
    { name: "Austria", code: "+43" },
    { name: "Czech Republic", code: "+420" },
    { name: "Hungary", code: "+36" },
    { name: "Romania", code: "+40" },
    { name: "Bulgaria", code: "+359" },
    { name: "Croatia", code: "+385" },
    { name: "Slovakia", code: "+421" },
    { name: "Slovenia", code: "+386" },
    { name: "Estonia", code: "+372" },
    { name: "Latvia", code: "+371" },
    { name: "Lithuania", code: "+370" },
    { name: "Iceland", code: "+354" },
    { name: "Luxembourg", code: "+352" },
    { name: "Monaco", code: "+377" },
    { name: "Malta", code: "+356" },
    { name: "Cyprus", code: "+357" },
    { name: "Morocco", code: "+212" },
    { name: "Algeria", code: "+213" },
    { name: "Tunisia", code: "+216" },
    { name: "Libya", code: "+218" },
    { name: "Kenya", code: "+254" },
    { name: "Tanzania", code: "+255" },
    { name: "Uganda", code: "+256" },
    { name: "Ghana", code: "+233" },
    { name: "Senegal", code: "+221" },
    { name: "Ethiopia", code: "+251" },
    { name: "Angola", code: "+244" },
    { name: "Mozambique", code: "+258" },
    { name: "Zimbabwe", code: "+263" },
    { name: "Jamaica", code: "+1-876" },
    { name: "Dominican Republic", code: "+1-809" },
    { name: "Cuba", code: "+53" },
    { name: "Haiti", code: "+509" },
    { name: "Bahamas", code: "+1-242" },
    { name: "Barbados", code: "+1-246" },
  ];
  